baseURL: 'https://zruiii.github.io'
title: Rayâ€™Log
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A fast, clean Hugo theme'
homepage: 'https://zruiii.github.io'
defaultContentLanguage: 'zh'
googleAnalytics: G-xxx
paginate: 10
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: ğŸ‘‹ Welcome to Rayâ€™Log
  # authorDescription: A clean, fast hugo theme focused on Reading
  info: A Self-introduction
  favicon: /images/avatar.png
  options:
    showDarkMode: true
    enableImgZooming: false
    enableMultiLang: true
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
  comments:
    giscus:
      enable: false
      repo: username/repo
      repo_id: xxx
      category: Announcements
      category_id: xxx
      mapping: pathname
      position: top
      lang: en # pick a language from https://github.com/giscus/giscus/tree/main/locales
    utteranc:
      enable: false
      repo: username/xxx
      issueTerm: pathname
  analytics:
    google:
      SiteVerificationTag: xxx
    umami:
      enable: true
      website_id: d55626b6-2157-4767-b84b-5f71e5d62ac1
      url: https://umami-lime-nu.vercel.app/hugo-ladder
  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything â€“- question, appreciation, information, or even humor.
  social:
    - name: GitHub
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/zruiii'
    # - name: Dashboard
    #   pre: >-
    #             <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-box"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>
    #   url: 'https://xxx'
languages:
  en:
    contentDir: content/en
    languageName: EN
    menu:
      main:
        - name: Blog
          url: /blog
          weight: 1
        - name: Tags
          url: /tags
          weight: 2
        - name: Archive
          url: /archives
          weight: 3
        - name: Guestbook
          url: /guestbook
          weight: 4
        - name: Dashboard
          url: https://umami-lime-nu.vercel.app/dashboard
          weight: 5
  zh:
    contentDir: content/zh
    languageName: ä¸­
    author: Ladder ä¸»é¢˜
    params:
      # authorDescription: ä¸€ä¸ªç¾è§‚ï¼Œå¿«é€Ÿå¹¶ä¸”ä¸“æ³¨äºé˜…è¯»çš„ä¸»é¢˜
      info: "å“ˆå–½ï½å¤§å®¶å¥½ï¼Œæˆ‘æ˜¯æŸ¥ç¿(Ray)ï¼Œä¸€ä¸ªçƒ­è¡·äº§å“çš„AIç®—æ³•å·¥ç¨‹å¸ˆã€‚\nè¿™é‡Œä¸»è¦åˆ†äº«ä¸¤ä»¶äº‹ï¼š1.ä¸ªäººçš„AIç®—æ³•å­¦ä¹ å¿ƒå¾—+å·¥ç¨‹å®è·µã€‚2.åŠªåŠ›æ‰“é€ è‡ªå·±çš„AIåŸç”Ÿåº”ç”¨ã€‚åšæŒåŸåˆ›ï¼Œäº‰å–å‘¨æ›´ğŸš€"
      guestbook:
        title: "ç•™è¨€æ¿"
        description: "æ‚¨çš„è¯„è®ºï¼Œä¼šè®©è¯¥ç½‘ç«™æ›´ç²¾å½©ï¼"
    menu:
      main:
        - name: æ–‡ç« 
          url: /blog
          weight: 1
        - name: åˆ†ç±»
          url: /tags
          weight: 2
        - name: å†å²æ–‡ç« 
          url: /archives
          weight: 3
        - name: ç•™è¨€æ¿
          url: /guestbook
          weight: 4
        - name: ç½‘ç«™ç»Ÿè®¡
          url: https://umami-lime-nu.vercel.app/dashboard
          weight: 5
taxonomies:
  series: series
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true